### PR TITLE
Maki icons

### PR DESCRIPTION
**Pull request by v1r0x**
This PR is aimed to fix both #13 and #52.

The maki icons are now included as submodule and thus not loaded externally. Also the pink marker has been removed and the icons are displayed without any marker.
What keeps this PR from merging (beside testing and review of course ;)) is a list of useful POIs and then display them depending on a certain zoom level.
This should also replace the current "Places" behaviour in the nav bar. Instead giving the user a list with POIs (which will be done depending on the zoom level) to show the user can disable/enable all POIs at once.

Comments, criticism and opinions are more than welcome :)
cc @jancborchardt @Henni @DJaeger

### CODE REVIEW

**Comment by Henni** [comment]
I'm not sure if `git submodule` is the best solution here.
I currently have two problems with this approach:
1. I haven't been able to get the icons. Currently my img/maki directory is completely empty.
2. It looks like there is a large overhead in the maki repository. We will probably only use a small portion of it.

Maybe `npm` or `bower` would be better.

**Comment by v1r0x** [comment]
> 2. It looks like there is a large overhead in the maki repository. We will probably only use a small portion of it.

Good point. I've never really used `npm` or `bower`. Do you have any experience and could replace the submodule approach?

**Comment by v1r0x** [comment]
Current version, fyi :)
Hope you like the new popup style, @jancborchardt 

maki-popup

**Comment by Henni** [comment]
@v1r0x do you use the PNGs or SVGs of maki?

**Comment by v1r0x** [comment]
Currently PNGs, but we could switch to SVGs if we integrate them using `npm` or `bower`

**Comment by Henni** [comment]
#118 includes the png icons via bower. Please review

**Comment by jancborchardt** [comment]
Let’s directly use SVG, as we do not need to support any browser which doesn’t support SVG.

Nice on the popup style and icons! Are the icons also available with a slight white border so they differentiate better from the map and when they overlay?

**Comment by v1r0x** [comment]
> Nice on the popup style and icons! Are the icons also available with a slight white border so they differentiate better from the map and when they overlay?

I think we have to do this by ourselves. Is it possible to add a CSS border to SVG images?

**Comment by jancborchardt** [comment]
We can add a simple thing via CSS, for example:
```
.maki-icon (or whatever the class is) {
  background: #fff;
  border: 1px solid #fff;
  border-radius: 3px;
}
```

**Comment by v1r0x** [comment]
If it doesn't look ugly I think this would be the best solution. Or if you are bored you can edit all icons :D

**Comment by v1r0x** [comment]
I already removed the maki submodule. Best would be to merge master into this branch and add the border mentioned by @jancborchardt , right?

**Comment by Henni** [comment]
Instead of merging master you could/should rebase this branch on top of master.
This keeps the history clean. Feel free to ask me if you need help with this.

**Comment by v1r0x** [comment]
Added a class for the marker icons. What do you think? @jancborchardt @Henni 
maki-icons

**Comment by v1r0x** [comment]
Is there anythink left in this PR? Could you please review it? Any thoughts about the icon background? @jancborchardt @Henni

**Comment by Henni** [comment]
Large amount of console output:
image
The first error *might* be related to https://github.com/owncloud/maps/pull/111#issuecomment-179277907

**Comment by v1r0x** [comment]
@Henni the `Uncaught TypeError` errors should be fixed. Any idea how to throttle/queue the API calls? Currently I iterate over my array using an `$.each` loop.

**Comment by Henni** [comment]
The api calls aren't part of this PR, are they?
So maybe we should fix this in a separate PR.

**Comment by v1r0x** [comment]
I replaced the whole POI stuff in this PR, so basically it is a part of this PR. But we also have to include all missing POI types. So we could close this PR and only fix #52 and fix #13 including the api calls in another PR.

**Comment by Henni** [comment]
Let's do this then!
One last squash and this should be ready to merge

**Comment by v1r0x** [comment]
Ready to merge?

**Pull request merged**
