### PR TITLE
Add basic favorite functionality

### LINKED ISSUE #9: Favorites
It should be possible to set points as favorites. They could be shown with star markers on the map, and this layer could be possible to disable in the sidebar.

Similarly, Contacts addresses could be shown as favorites by default (or at least the addresses of the contacts you set as favorite in the Contacts app).

cc @brantje

### PR DESCRIPTION
**Pull request by v1r0x**
moved branch to the original repo, related to #9

### CODE REVIEW

**Comment by Henni** [comment]
I fixed some issues with your code:
1. we need to use setters. Otherwise the mapper doesn't persist the changes in the database
2. I fixed inconsistent naming of $lon/$lng
3. userId has to be named user_id in the table (see [Database Entities](https://doc.owncloud.org/server/8.2/developer_manual/app/database.html?highlight=database#entities))

**Comment by v1r0x** [comment]
> I fixed some issues with your code:

Thanks!

> 3. userId has to be named user_id in the table (see Database Entities)

I had it like this in the first place, but everywhere I saw `userId` instead of `user_id` so I changed it, but good to know :)

**Comment by v1r0x** [comment]
Can we merge this?

**Comment by Henni** [comment]
@v1r0x Please remove the debug outputs first and squash the commits.

**Comment by v1r0x** [comment]
@Henni done

**Comment by Henni** [comment]
Looks good to me :+1: 

Can we get another review, please? @brantje @DJaeger 

short remark: this doesn't completely fix #9, but is a first step towards it (see https://github.com/owncloud/maps/issues/9#issuecomment-157835452).
This PR implements the option to add favorites. Another PR will actually display them.
Are you already working on this @v1r0x ?

**Comment by v1r0x** [comment]
I edited my comment in OP.

@Henni Yes, already started, but I'd like to discuss/ask some things in the issue to decide how to implement it

**Comment by v1r0x** [comment]
Can anyone else review this, so we can move to the next step of #9 ? :)

cc @DJaeger @brantje @jancborchardt

**Comment by jancborchardt** [comment]
We can go for single thumbs-up reviews for now. :) We’re not enough people yet for consistent 2-thumbs-up reviews, and we don’t have a release yet.

**Pull request merged**
