### PR TITLE
Open Popup on hover

### LINKED ISSUE #105: Open Place popups on hovering the marker instead of click
For quicker interaction, we should open the popups directly when hovering the marker (and close them again when mousing out). When clicking the place marker though, they could stay »pinned« open, and only close on clicking the X close icon.

Found some resources on how to do that:
- https://gis.stackexchange.com/questions/31951/how-to-show-a-popup-on-mouse-over-not-on-click
- https://github.com/Leaflet/Leaflet/issues/1674

We can then use single click to select other places, instead of the pretty difficult to find long-click.

### PR DESCRIPTION
**Pull request by v1r0x**
fixes #105 

This PR opens/closes the popup on hover. It stays open if the user hovers over the popup. If the user hover only over the marker the popup will close (on mouseout).

Works good for me, except a js TypeError. Don't know why...

What do you think (except the error), @jancborchardt ?

### CODE REVIEW

**Comment by jancborchardt** [comment]
> It stays open if the user hovers over the popup.

Nice behavior, good call!

However there’s one strange behavior: When you hover a marker, the popup opens. When you then click it (this can happen directly after the hover because ppl might be used to it), the popup closes. It should then be permanently open though, just like when hovering the popup itself.

Also, can you then change the POI popup to show on single click instead of long click?

**Comment by v1r0x** [comment]
The easiest way would be to deactivate close on marker click completely. This also seems to be a comprehensible behaviour.

Yes, should be easy to modify.

**Comment by jancborchardt** [comment]
True, let’s try with closing on marker click deactivated. The close cross should suffice.

**Comment by v1r0x** [comment]
Seems that this is not possible without modifying the leaflet source...The best I could get was a reopen of the popup. I'll commit it so you can test it.

**Comment by jancborchardt** [comment]
After a bit of testing, it seems that not messing with the click event makes it smoother. So  11f9941 can be reverted. :)

However one thing is strange and feels glitchy: Hovering over the marker, the popup shows. Then moving across to the popup makes the popup flash once. Can we get rid of that?

(Also another thing, but probably for a future pull request: When single-clicking somewhere, sure the data for the POI has to be loaded first until the popup can be shown. But the place marker should immediately be displayed for fast feedback.)

**Comment by v1r0x** [comment]
> However one thing is strange and feels glitchy: Hovering over the marker, the popup shows. Then moving across to the popup makes the popup flash once. Can we get rid of that?

Havn't noticed this. I'll test it later and (if it exists for me) try to fix it.

> (Also another thing, but probably for a future pull request: When single-clicking somewhere, sure the data for the POI has to be loaded first until the popup can be shown. But the place marker should immediately be displayed for fast feedback.

Should be easy to fix, maybe just one line of code. So no separate PR, in my opinion. :)

**Comment by v1r0x** [comment]
I could not reproduce the popup flash. But adding the marker immediately after the click should work.

**Comment by jancborchardt** [comment]
Ok, let's merge and fix additional stuff going forward. :)

**Pull request merged**
