### PR TITLE
update authors list, up max-version

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @v1r0x @Henni

### CODE REVIEW

**Comment by v1r0x** [comment]
Where is my name? :( I think you confused Lennard with me ;)
Beside that **HUGE** mistake (:P) :+1:

**Comment by jancborchardt** [comment]
@v1r0x either I’m completely stupid and really got your name wrong, or you want to be credited as v1r0x? ;D

**Comment by jancborchardt** [comment]
:D WTF why did I confuse that … I guess because you rarely have your name anywhere …

**Comment by jancborchardt** [comment]
@v1r0x fixed … I guess the confusion came from the »Ros…« which both of your names start with. :D
Or modify it if you want your full name to be used. :)

**Comment by v1r0x** [comment]
@jancborchardt 
> :D WTF why did I confuse that … I guess because you rarely have your name anywhere …
I'm invisible ;)

Added my real name. Feel free to merge

**Comment by jancborchardt** [comment]
@v1r0x sorry again ;D

**Pull request merged**
