### PR TITLE
Updated readme

### LINKED ISSUE #35: update Readme
Please add a small description of what the user can expect from this app.

Thanks.

### PR DESCRIPTION
**Pull request by v1r0x**
fixes #35

### CODE REVIEW

**Comment by v1r0x** [comment]
Should be the correct commit...

please review
@jancborchardt @Henni @DJaeger @brantje

**Comment by Henni** [comment]
Looks good to me :+1:

**Comment by DJaeger** [comment]
Looks good to me :+1:

**Comment by jancborchardt** [comment]
Ohhh, awesome on the screenshots! :)

**Pull request merged**
