### PR TITLE
position GPS and zoom controls in bottom right

### PR DESCRIPTION
**Pull request by jancborchardt**
Move them away from the search field because there’s too much going on otherwise.

Please review @v1r0x @Henni

### CODE REVIEW

**Comment by v1r0x** [comment]
In my opinion we could remove the zoom buttons completely. Otherwise :+1:

**Comment by jancborchardt** [comment]
Yeah, I tend to agree. Scrolling and double-tapping to zoom is pretty common these days. We can always add them back when people complain. Will adjust.

**Comment by v1r0x** [comment]
I commented it out for now. Ok?

**Comment by jancborchardt** [comment]
:D I just changed it locally and force pushed without seeing your changes. Basically did the same. ;)

Also I moved the GPS icon back to the top right because without the zoom controls, it feels like the location action should be near the search field after all. (Also because the routing could start from the current location.)

**Pull request merged**
