### PR TITLE
Refactor Database Mappers

### PR DESCRIPTION
**Pull request by Henni**
I refactored the database mappers.
This PR replaces the current implementation with entities for devices and locations and their corresponding mappers.

### CODE REVIEW

**Comment by Henni** [comment]
At the moment the implementation is broken, but I have no idea why. Somehow the dependency injection doesn't work anymore. Ideas on how to fix this are welcome!
image

**Comment by v1r0x** [comment]
From looking at the changes I see no problem, but I'm no expert in DI ;)
Will have a look at it as soon as I have some free time

**Comment by jancborchardt** [comment]
@DJaeger @brantje @poVoq can you also have a look here?

**Comment by DJaeger** [comment]
I will have a look as soon as I have some time.

**Comment by jancborchardt** [comment]
@Henni is this pull request still work in progress or done from your point of view?

**Comment by Henni** [comment]
We just have to find out why the error occurs. Everything else is done.

Maybe someone who knows a bit about the internals of dependency injection can help.

**Comment by LEDfan** [comment]
Hey, never checked out this app but saw this issue on IRC. I have solved this error in the commit I made, I hope this isn't a problem?

Some general tips on DI and autoloading:
 - use all lowercase for directorie and file names
 - try to type cast. (e.g. OCP\IDb for $db https://github.com/owncloud/maps/commit/34979551480ce0a40e510ccb67884e622d65719a#diff-9d6c69654961b63ec357264921a1724cR19 )  - never try to register core functions in your own DI container this will soon or later cause problems.

For reference the documentation of ownCloud: https://doc.owncloud.org/server/8.2/developer_manual/app/container.html and of Pimple (the DI injection container oC use): http://pimple.sensiolabs.org/

**Comment by Henni** [comment]
@LEDfan thanks for the help!
So I'll replace the filenames with lowercase filenames.

Can you explain to me why the error message said something about the cachemanager while it was obviously a problem with the location manager?

**Comment by LEDfan** [comment]
@Henni is the fix working for you?

**Comment by Henni** [comment]
@LEDfan Yes the fix is working for me. Again thanks for the help!

**Comment by BernhardPosselt** [comment]
IDb is deprecated, use IDBConnection ;)

**Comment by Henni** [comment]
The pull request is now almost complete. I just want to remove the last occurence of the locationmanager.

Therefore I still have to figure out how to return arrays of Entities as a JSON Response.

**Comment by Henni** [comment]
@BernhardPosselt thanks for the hint.
We'll have to refactor the `CacheManager` as well and replace it with a `CacheMapper` which uses `IDBConnection` instead.

**Comment by Henni** [comment]
Ready to review!
The `CacheManager` will be refactored in a seperate PR (Issue #72).

cc @v1r0x @DJaeger @brantje @poVoq

**Comment by jancborchardt** [comment]
@v1r0x @DJaeger @brantje @poVoq can you review this? :)

**Comment by v1r0x** [comment]
I'm back from my holiday and can hopefully review this in the next days

**Comment by Henni** [comment]
@DJaeger do you think we can merge this. This would simplify future development.

**Comment by DJaeger** [comment]
I will review this later day.
I'm still working thought my pending mails...

**Comment by Henni** [comment]
@irgendwie

**Comment by irgendwie** [comment]
LGTM :+1:

**Pull request merged**
