### PR TITLE
Change marker/icon on fav/unfav as visual feedback

### LINKED ISSUE #88: Adding smth to favorites should show that marker as feedback
When you don’t have the favorites layer enabled, it’s not apparent if the item was added to favorites. To fix this, maybe just enabling the favorites layer will do the trick. At the very least, show the marker for that favorite which was set just now as feedback.

cc @Henni @v1r0x :)

### PR DESCRIPTION
**Pull request by v1r0x**
fixes #88

Please test and review. :)

cc @jancborchardt @Henni @DJaeger

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice! (Fixed a syntax error ;) just some small things:

- [ ] the favorite should already be saved when the star is clicked, not only after the name is put in. The name input is basically an editing after saving, not before.
- [ ] the marker of a new favorite is displayed smaller than the existing ones.
- [ ] when favoriting, all the detail info is suddenly gone from the popup which is quite confusing. We need to fix that by unifying the popup look for 0.1, will open a separate issue about that.

**Comment by v1r0x** [comment]
> the favorite should already be saved when the star is clicked, not only after the name is put in. The name input is basically an editing after saving, not before.

IMO it should be as it is right now or save the favorite with the name of the marker and then add a edit icon to rename it.
I think don't force the input field and let the user decide whether they want to edit it or not. What do you think?

> the marker of a new favorite is displayed smaller than the existing ones.

This should be fixed with your new, nice markers ;)
Currently they don't have the same size and I adjusted it to match the `png`.

**Comment by jancborchardt** [comment]
Yeah, agree on not forcing the input field. Just display an .icon-rename right next to the name. Then we'll merge :)

**Comment by v1r0x** [comment]
The button looks a bit ugly and should be placed beside the title but not inside the `<h2>`, because this would make it harder to switch between `h2` and and input field. Could you do that @jancborchardt ? :)
Beside that the edit functionality is missing, I'll add it later ;)

**Comment by v1r0x** [comment]
I added the functionality and I like it! :)
This PR is now ready for test & review @jancborchardt @Henni @DJaeger

**Comment by Henni** [comment]
@v1r0x I'll take a look, but:
**This branch has conflicts that must be resolved**

**Comment by v1r0x** [comment]
@Henni thanks. I'll resolve them before merge and then push it.

**Comment by Henni** [comment]
Looks good to me (besides @jancborchardt's notes)
:+1:

**Comment by v1r0x** [comment]
the marker display error will be fixed after merging #104 ;)

**Pull request merged**
