### PR TITLE
Lots of layout improvements

### PR DESCRIPTION
**Pull request by jancborchardt**
- style contacts loading bar
- reorder left navigation items
- reduce POI categories to essentials (this is a bit broken but we should fix this properly in a separate issue, grouping categories to show as »restaurant« for example, and adding stuff like »wifi«.
- place search field over map, ref #2
- force mobile view, navigation hidden by default, copied from mobile.css, fixing #2 

Please review @v1r0x

### CODE REVIEW

**Comment by v1r0x** [comment]
Nice work!
I think we shouldn't close the side panel after the user clicks on a list item. Especially if the user clicks the contact layer the progress isn't visible. Rather it should close on a click on the map.

**Comment by jancborchardt** [comment]
True, at least on the desktop. There it should also not close on click on the map I think – only the menu toggle should do that.

**Comment by jancborchardt** [comment]
Can you maybe tweak the JS for that? Not sure I’m proficient enough to do that. :D

**Comment by v1r0x** [comment]
> Can you maybe tweak the JS for that? Not sure I’m proficient enough to do that. :D

Tomorrow. Shouldn't commit something at around 4am ;)
I'll have a look at gmaps and take a look at their side panel.

**Comment by v1r0x** [comment]
Couldn't find something in the code. Also I resized the browser window on master branch to force mobile css and then it didn't closed the nav bar. Don't know what's going on..

**Comment by jancborchardt** [comment]
Let’s merge it for now and improve going forward. :)

**Comment by Henni** [comment]
@jancborchardt didn't you or me create an issue for the hidden sidebar on desktop in the core repo?
Do you remember if and where?
If not we should do so as I think other apps might also like this functionality.

**Comment by jancborchardt** [comment]
Yeah, I think it might have been in the Calendar repo. Either way I would say we shouod experiment with it here first. Then check if it also works for Calendar, and then we could move it to core.

**Comment by Henni** [comment]
@jancborchardt sounds good to me :+1:

**Pull request merged**
