### PR TITLE
use url of contacts app for contact pictures

### PR DESCRIPTION
**Pull request by v1r0x**
(temporary?) fix for #57

### CODE REVIEW

**Comment by Henni** [comment]
This makes the maps app depend on the contacts app. This is probably not what we want.

**Comment by v1r0x** [comment]
This is not a new dependency

**Comment by jancborchardt** [comment]
In any case it should be totally optional. If the Contacts app is not installed, simply do not show the entry in the sidebar and deactivate the functionality.

This is something for a separate PR though it seems?

**Comment by Henni** [comment]
Yeah right. The difference between Maps & Contacts and Tasks & Calendar is that in this case the dependency isn't mandatory.

**Comment by jancborchardt** [comment]
Wow … seeing your contacts on the map with images is just pretty awesome! :) Works quite well! :+1: 

Regarding the dependency, I opened https://github.com/owncloud/maps/issues/59

**Comment by jancborchardt** [comment]
@Henni @brantje what do you think?

**Comment by Henni** [comment]
Looks great!
I had the issue that the sprite had blue borders at the right and bottom. But that's probably because my default browser zoom level is 125% and thus it's a browser issue.
So :+1: from me

**Comment by jancborchardt** [comment]
Great stuff @v1r0x, you're awesome! :)

Are you on IRC in our #owncloud-dev channel yet? (Freenode)

**Comment by v1r0x** [comment]
Thanks :)
Now I am

**Pull request merged**
