### PR TITLE
Added gallery, motel, museum and zoo MakiMarkerIcon mapper

### LINKED ISSUE #46: Type icons not found
Currently Maps gives some errors about not found type icons:
```
[…]
script.js?v=45360383019c34fc1b722568d8ed4110:960 Type icon not found: gallery
script.js?v=45360383019c34fc1b722568d8ed4110:960 Type icon not found: motel
script.js?v=45360383019c34fc1b722568d8ed4110:960 Type icon not found: museum
script.js?v=45360383019c34fc1b722568d8ed4110:960 Type icon not found: theme_park
script.js?v=45360383019c34fc1b722568d8ed4110:960 Type icon not found: zoo
```

@Brantje @DJaeger

### PR DESCRIPTION
**Pull request by DJaeger**
Mostly fixes #46

### CODE REVIEW

**Comment by DJaeger** [comment]
Now it completely fixes #46.

**Comment by jancborchardt** [comment]
@DJaeger awesome stuff! :) I’ll check it out later.

Are you also interested in collaborating on https://github.com/owncloud/maps/issues/13 to simplify the lists a bit?

**Comment by DJaeger** [comment]
I will try to fix and improve as much as my time allows. ;-)

**Comment by jancborchardt** [comment]
@DJaeger of course I forgot to mention that the log in #46 was only partial. If you open the JS console then you will see all these other things too ;)

```
Type icon not found: Electronics
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: Elektrohaushaltsgeräte
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: Fashion
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: Hema
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: Hockey
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: Kaugummi-Automat
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: Kaugummi-Automaten
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: Patissier
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: Shisha
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: Shoes
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: Sicherheitstechnik
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: Trödel
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: accessoires
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: alteration
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: animals
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: anime
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: antique
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: antiques
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: art_gallery
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: art_supplies
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: artist
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: audiologist
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: baby
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: baby_goods
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: bags
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: bakery
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: beauty
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: bed
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: bicycle_rental
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: board_games
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: boutique
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: brushes
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: callshop
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: camera
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: candle
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: candy
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: cannabis
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: car_parts
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: carpet
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: carrental
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: cd
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: ceramics
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: chandler
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: charity
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: cheese
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: chemist
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: christmas
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: cigar
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: cigarettes
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: circus
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: coffee
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: coffeemachines
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: coins
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: comics
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: communication
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: confectionery
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: crafts
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: currency_exchange
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: curtain
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: decoration
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: delicatessen
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: disused:butcher
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: dry_cleaning
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: electric
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: electrician
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: erotic
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: espresso_machine
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: estate_agent
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: fabric
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: fabrics
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: fashion
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: fire_extinguisher
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: fishing
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: floor
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: forrent
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: frame
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: framing
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: frozen_yoghurt
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: funeral_directors
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: games
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: garden_centre
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: generic
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: glass
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: glasses
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: glaziery
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: gramophone
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: grocery
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: haberdashery
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: handicraft
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: hardware
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: hats
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: health
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: hearing_aids
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: hearth
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: hemp_products
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: household
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: housewares
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: ice_cream
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: ink
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: interior
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: interior_decoration
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: interior_design
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: internetcafe
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: internet-tele-cafe
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: internet_cafe
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: jewellery
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: juice
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: key
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: knives
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: lamps
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: laundry
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: leather
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: lighting
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: lights
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: lingerie
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: lottery
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: make-up
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: mall
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: marine
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: massage
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: medical
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: medical_supply
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: metalworkshop
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: mobilephone service
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: motorcycle
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: music
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: musical_instrument
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: nail
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: nails
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: newsagent
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: no
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: office_supplies
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: organic
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: orthopedics
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: parquet
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: perfume
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: perfumery
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: photographer
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: photography
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: piercing
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: porcelain
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: pottery
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: printing
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: radiotechnics
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: rc_models
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: realestate
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: rental
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: scuba_diving
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: seafood
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: second_hand
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: seefood
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: sewing-machine
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: shoe_repair
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: skating
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: smartshop
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: snacks
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: soft_drugs
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: softdrugs
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: sok_shop
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: souvenirs
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: spiritual
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: sport_bet
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: sportsfood
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: stamps
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: stationery
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: stones
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: surf
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: tableware
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: tailor
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: tanning
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: tanning_salon
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: tatoo
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: tattoo
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: tea
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: telecom
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: telecommunication
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: telephone
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: textiles
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: thrift_store
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: ticket
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: tobacco
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: tobacconist
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: toko
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: traiteur
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: travelling
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: tyres
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: underwear
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: unknown
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: unused
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: vacant
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: watch
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: watches
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: wholesale
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: window_blind
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: wine
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: arts_centre
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: bicycle_rental
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: boat_rental
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: brothel
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: bureau_de_change
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: bus_parking
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: cafe
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: car_rental
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: car_wash
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: casino
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: charging_station
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: cinema
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: coffee_shop
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: coffeeshop
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: college
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: community_centre
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: dentist
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: doctors
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: drinking_water
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: driving_school
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: embassy
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: ev_charging
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: fablab
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: ferry_terminal
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: fitness_center
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: fountain
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: fuel
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: grit_bin
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: gym
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: health_centre
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: ice_cream
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: kitchen_studio
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: library
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: lost_found
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: money_transfer
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: nightclub
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: parking_entrance
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: pharmacy
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: physicaltherapy
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: police
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: public_building
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: sauna
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: studio
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: tanning
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: tanning_salon
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: taxi
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: telephone
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: theatre
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: toilets
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: university
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: vacant
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: vending_machine
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: veterinary
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: waste_basket
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: apartment
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: aquarium
script.js?v=dfb60d3fbf0c31bbfdbdbd3498564e8e:961 Type icon not found: citytour
```

**Comment by jancborchardt** [comment]
`Type icon not found: cannabis`
:D

**Comment by jancborchardt** [comment]
@DJaeger can you adjust the pull request to include all these icons? :)

**Comment by DJaeger** [comment]
I will check that.
What do think of searching for a icon collection containing all icons for all tags?
Currently we combine two collections.

**Comment by jancborchardt** [comment]
I think we have to reduce the list of the POI’s anyway, as said in https://github.com/owncloud/maps/issues/13. Then it also gets easier looking for a kit which only has the relevant ones.

For example, we don’t need POIs for every single `waste_basket`, `grit_bin`, `tanning_salon`, `tea`, `stones`, `cannabis`, `sports_bet` etc.
And some duplicates like `coffe_shop` and `coffeeshop` should be combined.

**Comment by jancborchardt** [comment]
@DJaeger any update? Then we could merge this and fix the nonsensical console errors. :)

**Comment by DJaeger** [comment]
Sorry, have currently no time for this.
Please wait some days.

**Comment by jancborchardt** [comment]
@DJaeger sure, no problem. :)

**Comment by jancborchardt** [comment]
I’m merging this for now, we can always improve later. :)

**Pull request merged**
