### PR TITLE
Minmax version

### LINKED ISSUE #116: »This app has no minimum ownCloud version assigned. This will be an error in ownCloud 11 and later.«
@v1r0x @Henni @brantje what’s the minimum version we run on? We should put that in the info.xml

### PR DESCRIPTION
**Pull request by v1r0x**
fixes #116 

cc @jancborchardt @Henni

### CODE REVIEW

**Comment by Henni** [comment]
@v1r0x we have to tell travis not to test core_branch 8 and 8.1

**Comment by jancborchardt** [comment]
Looks good :+1:

**Comment by v1r0x** [comment]
> @v1r0x we have to tell travis not to test core_branch 8 and 8.1

Feel free to commit ;) I think you have more experience in this.

**Comment by Henni** [comment]
I already looked for it, but have no idea how to set the core_branches.
Maybe @DeepDiver1975 can help out.

**Comment by DeepDiver1975** [comment]
> I already looked for it, but have no idea how to set the core_branches.

rebase any kill the corresponding lines in .travis.yml

**Comment by v1r0x** [comment]
:+1:

**Comment by v1r0x** [comment]
Everything done to fix #116?

**Pull request merged**
