### PR TITLE
adjust popup radius to standard ownCloud 3px

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @v1r0x @Henni @brantje @DJaeger

### CODE REVIEW

**Comment by jancborchardt** [comment]
Yo folks, simple review. :)

**Comment by v1r0x** [comment]
is `.leaflet-popup-content-wrapper` anywhere in the code? Couldn't find it. Maybe we can delete it instead ;)

**Comment by jancborchardt** [comment]
Yeah, it’s used by the leaflet library. The popup is used for showing details of POIs and contacts. :)

**Comment by v1r0x** [comment]
Ah ok, the name is generated and not hardcoded.
in the leaflet css file there is already a definition for this:
https://github.com/owncloud/maps/blob/master/css/leaflet/leaflet.css#l390-l394
should we adjust it there or in the `style.css`?

But looks good, :+1:

**Comment by Henni** [comment]
looks good :+1:

@v1r0x We shouldn't change any of the leaflet files so that we can just replace them if we want to update to a newer version.

**Comment by v1r0x** [comment]
@Henni good point :+1:

**Pull request merged**
