### PR TITLE
add custom favicon

### PR DESCRIPTION
**Pull request by jancborchardt**
But for some reason it is not displayed. Does this have something to do with the ico fallback we have to do in core for IE8,9,10? I did add the favicon.ico though.

Please check @owncloud/designers @MorrisJobke @v1r0x @Henni

### CODE REVIEW

**Comment by MorrisJobke** [comment]
> But for some reason it is not displayed. Does this have something to do with the ico fallback we have to do in core for IE8,9,10? I did add the favicon.ico though.

Yep. We now only support ico files.

**Comment by jancborchardt** [comment]
I did add the ico though, as said. @MorrisJobke does it work for you?

**Comment by MorrisJobke** [comment]
> I did add the ico though, as said. @MorrisJobke does it work for you?

No and yes - you need following fix: https://github.com/owncloud/core/pull/21482

**Comment by jancborchardt** [comment]
Nice! Can you test with the fix from core and give your +1 on this? Cc @v1r0x

**Comment by MorrisJobke** [comment]
:+1:

**Comment by v1r0x** [comment]
Looks good :+1:

**Pull request merged**
