### PR TITLE
Fix address lookup

### PR DESCRIPTION
**Pull request by v1r0x**
lookup url was `street x city` which didn't work and only searchs for street.

### CODE REVIEW

**Comment by v1r0x** [comment]
Sorry, only the last commit (475aeba) should be pat of this PR. Is there a way to delete the other two from this PR?

**Comment by Henni** [comment]
@v1r0x you can remove the commit locally and force push afterwards

**Comment by v1r0x** [comment]
Thanks @Henni Should be correct now

**Comment by jancborchardt** [comment]
Still works well :) :+1:

**Pull request merged**
