### PR TITLE
Reorganize phpunit

### LINKED ISSUE #80: Error while running phpunit
While running : 

phpunit tests/

I get : 
PHP Fatal error:  require_once(): Failed opening required '/var/www/owncloud/apps/maps/tests/../../../3rdparty/Pimple/Pimple.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/owncloud/apps/maps/tests/autoloader.php on line 12

### PR DESCRIPTION
**Pull request by Henni**
There are currently (almost) no tests.
This pull request simply reorganizes the test files.

Until now the phpunit.xml in the root folder wasn't used at all and lead to errors if one tried ( see #80 ).
Now this file is actually used and i moved all tests from the subfolder `tests/unit/` to `tests/`.

The only existing test is for the pagecontroller and isn't complete.
So let's start building tests!

cc @nutzmdm @v1r0x @DJaeger 
fixes #80

### CODE REVIEW

**Comment by jancborchardt** [comment]
@nutzmdm can you test & review this since it fixes your reported issue #80 :)

**Comment by Henni** [comment]
@v1r0x could you take a look, please?
This PR would allow us to start writing tests for our backend.

**Comment by v1r0x** [comment]
@Henni any instructions what to do? I tried to test it, but got a couple of errors.

**Comment by Henni** [comment]
Which errors did you get?

**Comment by v1r0x** [comment]
`PHP Fatal error:  Class 'OCA\Maps\AppInfo\Application' not found in /home/me/foo/maps/tests/controller/pagecontrollertest.php on line 27` if I try to run it from inside the tests/ folder

**Comment by Henni** [comment]
@v1r0x The idea is that you can now run `phpunit` from the root folder (`maps/`).

**Comment by v1r0x** [comment]
@Henni then I get this error:
`Cannot open file "/var/www/html/owncloud/apps/maps/../../tests/bootstrap.php".`

**Comment by Henni** [comment]
@v1r0x Could you verify that this file actually doesn't exist?

**Comment by v1r0x** [comment]
the folder tests in the oc root folder does not exists. Do I need something for that?

**Comment by Henni** [comment]
@v1r0x You probably installed owncloud using the archives from owncloud.org which don't contain tests.
Think about using [ocdev](https://github.com/owncloud/ocdev) instead which actually clones the git repo and has some additional functionality like code checks.

**Comment by v1r0x** [comment]
@Henni thanks for the link, will test later

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
