### PR TITLE
Verify device id hash exists before saving location tracking updates

### PR DESCRIPTION
**Pull request by mozzwald**

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@brantje merge?

**Comment by brantje** [comment]
Can you rebase?

**Comment by DeepDiver1975** [comment]
> Can you rebase?

@mozzwald THX

**Comment by jancborchardt** [comment]
@mozzwald can you rebase this on current master?

Otherwise @brantje @DJaeger @Henni maybe just one of you rebase it locally and push it to a branch here that we can review. :)

**Comment by jancborchardt** [comment]
Closing in favor of https://github.com/owncloud/maps/pull/56 :) – @mozzwald your commits will be preserved.

**Pull request closed without merging**
