### PR TITLE
'Remove favorite' functionality

### LINKED ISSUE #95: Ability to remove favorites
@v1r0x ;)

### PR DESCRIPTION
**Pull request by v1r0x**
fixes #95

### CODE REVIEW

**Comment by v1r0x** [comment]
@jancborchardt @Henni @DJaeger Could you please review this? :)

**Comment by jancborchardt** [comment]
Nice! Just a few details:
- [ ] I would say the popover should stay open when unfavoriting, just the star should then be grey. Since you might still want to view it, or pressed it by accident. It’s a bit jarring to just directly close it. Not entirely sure about it, but seemed a bit odd. The marker should then also transform into a normal marker
- [ ] All the favorite markers flash once, I guess because they are all reloaded? If possible, only the relevant marker should be removed.

**Comment by v1r0x** [comment]
Replacing the star-icon is rather easy, but replace the marker icon seems to be impossible. Maybe creating a new marker and force to open the popup might be possible as workaround, but I don't know. If this is not possible I would use the current solution and delete (and thereby close) the marker.

**Comment by v1r0x** [comment]
We should fix this in #88 since there it should be the same. Are you ok with this? And can we merge this for now then?

**Comment by jancborchardt** [comment]
Yup! :)

**Pull request merged**
