### PR TITLE
added possibility to load gpx track files

### PR DESCRIPTION
**Pull request by v1r0x**
refs #39 
gpx files have to be in `MyTracks` folder (in the files app root) and will be loaded on a click on "Contacts" (I know this is not a good way, but this was only for testing ;))

thanks @oparoz for your help! :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
Maybe better: Add a sidebar entry for »Load GPX file« and make it open a filechooser. Similar how we do in the Mail app for attachments.

**Comment by v1r0x** [comment]
I think loading one file after another is not the best solution supposed the user wants to add several files.
What about: Keeping the `MyTracks` folder and let the user add subfolders containing `gpx` files and then show an entry "Load GPX Files" (similar to Amenity, Tourism and Shops) and on click open sub-entries (named after the subfolders of `MyTracks` and the user can toggle these sub-entries (similar to Amenity>atm,bank,bar,...)?

**Comment by DJaeger** [comment]
How about offering all the following:
* a separate section showing tracks contained in the MyTracks folder as choosable layers
* a filehandler to open a file directly from files app
* button to choose file to upload and import

**Comment by v1r0x** [comment]
> a separate section showing tracks contained in the MyTracks folder as choosable layers

Each file as entry or subfolders as entry?

> a filehandler to open a file directly from files app
> button to choose file to upload and import

Sounds good

**Comment by DJaeger** [comment]
I would use only one of these solutions:
*  Read a folder and let the user choose which files to show and save imports as file to this folder.
* Read tracks to show from db and let the user import from owncloud or local.

I would prefer to use the database as it wouldn't mess up so much and we could extend it much simpler, for example with some metadata, if we want so later.
Also we could use a single class to read devicelocation data and other tracks, by saving the device hash as metadata and take care of it by an extending class.

If we would use a folder anyway I would show all items in its root folder in one if these ways:
* If its a file show it as choosable layer with a track-/gpx-icon
* If its a folder show it as expandable item which shows all contained items like the files in the top folder.

So allow the files to be saved in up to two levels.
Show folder on above the files.

**Comment by v1r0x** [comment]
> Maybe better: Add a sidebar entry for »Load GPX file« and make it open a filechooser. Similar how we do in the Mail app for attachments.

@jancborchardt  Can you comment the corresponding lines? :)

**Comment by v1r0x** [comment]
I splitted the "Show GPX-Tracks" into 3 sub-items
- Load from Folder
- File Chooser
- Upload
I'll push it, as soon as it is finished. Then someone can implement the DB-stuff. :)

**Comment by v1r0x** [comment]
@jancborchardt found it!

**Comment by v1r0x** [comment]
Is now split into
- loading from MyTracks folder (works)
- select file using OC.dialogs.filepicker (works)
- upload a file (not implemented)

@jancborchardt what is the `modal` flag in the filepicker?
@DJaeger @Henni @jancborchardt any idea how to upload a file? (if possible)

**Comment by jancborchardt** [comment]
Btw, can you contact the author of the GPX viewer app https://apps.owncloud.com/content/show.php?action=content&content=168505 – seems to be @Frank1604 with the app at https://github.com/Frank1604/files_gpxviewer_extended

It would be really cool if you could collaborate! :)

**Comment by v1r0x** [comment]
I already wrote him (in a comment on the apps page) and totally forgot to ask him directly. And yes, it would be really cool! :)

**Comment by Frank1604** [comment]
I have just discovered this here. Give me a few days to check out what's the question and what i can do. ;)
I love to collaborate if this can make things better.

**Comment by v1r0x** [comment]
@Frank1604 any news? If you have any questions, you can ask me on the owncloud-dev irc channel

**Comment by Frank1604** [comment]
No, still nothing new. My son had a serious accident and is in hospital and I have a lot of trouble at the moment. I have not yet managed to look at what I can do for you. Can you please give me a summary?

**Comment by v1r0x** [comment]
Sorry to hear that. Hope he gets well soon!

This is an openstreetmap based app which shows addresses, contacts and POIs.
Another feature is loading gpx/kml/... files.
Maybe we could integrate your gpx track feature and code into this app.

**Comment by Frank1604** [comment]
Yes I hope so too. By the way, never ride a bike on a halfpipe. ;)
I have installed the app and viewed in more detail. I think I now understand what is meant, and I already have a rough idea how it should look.
I hope I have asap time to work on it.

**Comment by v1r0x** [comment]
I will create a new PR for this with a branch in this repo, not my fork

**Comment by jancborchardt** [comment]
@Frank1604 sounds like your son could like Vittorio Brumotti ;) https://www.youtube.com/watch?v=WhQovX1zP2E

Also, basically a short description of this Maps app is that we want to replace the basic use cases of Google Maps. Looking for places, how to get there, storing favorites, etc.

**Pull request closed without merging**
